title      : scott.cgi
lang       : zh
description: 编程写作 / 迭代认知 / 执行计划
copyright  : © 2018 - 2025 scott.cgi All Rights Reserved

nav:
 - name: 中文
   link: /
 - name: 隐私政策
   link: /privacy-zh/
 - name: 编程人生
   link: /code-life/
 - name: En
   link: /about/
 - name: 赞赏支持
   link: /donate/
