title      : scott.cgi
lang       : zh
description: 编程写作 / 迭代认知 / 执行计划
copyright  : © 2018 - 2025 scott.cgi All Rights Reserved

nav:
 - name: 中文
   link: /
 - name: 环境配置
   subnav:
    - name: WSL替代虚拟机指南
      link: /[01-05]WSL替代虚拟机指南：ARM开发板交叉编译与TFTP通信配置/
    - name: Git简易工作流
      link: /[06]Git简易工作流：从本地配置到Gitee代码推送/
    - name: Windows原生运行Linux
      link: /[07]告别虚拟机：Windows原生运行Linux服务器代码指南/
    - name: LVGL移植指南
      link: /[08]【实战】LVGL 最新(9.3)移植指南：嵌入式Linux帧缓冲环境配置与开发板部署/
    - name: LVGL官方Demo解析
      link: /[09]【拓展】LVGL官方Demo全解析：从音乐播放器到高分辨率渲染/
    - name: LVGL模拟器搭建
      link: /[10]【实战】LVGL模拟器搭建指南：VSCode+MinGW构建+CMake自动化/
    - name: VMware网络配置
      link: /[指南]VMware-简单网络配置指南/
    - name: Sqlite3配置（暂空）
      link: /[指南]Linux与开发板安装sqlite/
    - name: 解决Qt应用界面过大问题
      link: /解决Qt应用界面过大问题：Windows下高DPI缩放的正确配置方法/
 - name: 内功修炼
   subnav:
   - name: C语言基础复习
     link: /C语言基础复习/
   - name: C语言数组与函数递归复习
     link: /C语言数组与函数递归复习/
   - name: C语言指针复习
     link: /C语言指针复习/
  #  - name: 正则表达式与bash
  #    link:
  #  - name: make和cmake编写
  #    link:
  #  - name: 文件IO与系统IO
  #    link:
  #  - name: lvgl学习
  #    link:
  #  - name: 进程间通信
  #    link:
  #  - name: 并发
  #    link:
  #  - name: 网络编程
  #    link:
  #  - name: 数据库
  #    link:
  #  - name: 
  #    link:
 - name: 其他内容
   subnav:
   - name: 隐私政策
     link: /privacy-zh/
   - name: 编程人生
     link: /code-life/
   - name: En
     link: /about/
   - name: 赞赏支持
     link: /donate/
