title      : star_plain
lang       : zh
description: 编程写作 / 迭代认知 / 执行计划
copyright  : © 2018 - 2025 star_plain All Rights Reserved

nav:
 - name: 环境配置
   subnav:
    - name: WSL替代虚拟机指南
      link: /[01-05]WSL替代虚拟机指南：ARM开发板交叉编译与TFTP通信配置/
    - name: Git简易工作流
      link: /[06]Git简易工作流：从本地配置到Gitee代码推送/
    - name: Windows原生运行Linux
      link: /[07]告别虚拟机：Windows原生运行Linux服务器代码指南/
    - name: LVGL移植指南
      link: /[08]【实战】LVGL 最新(9.3)移植指南：嵌入式Linux帧缓冲环境配置与开发板部署/
    - name: LVGL官方Demo解析
      link: /[09]【拓展】LVGL官方Demo全解析：从音乐播放器到高分辨率渲染/
    - name: LVGL模拟器搭建
      link: /[10]【实战】LVGL模拟器搭建指南：VSCode+MinGW构建+CMake自动化/
    - name: VMware网络配置
      link: /[11]VMware-简单网络配置指南/
    - name: Sqlite3配置（暂空）
      link: /[指南]Linux与开发板安装sqlite/
    - name: 解决Qt应用界面过大问题
      link: /[12]解决Qt应用界面过大问题：Windows下高DPI缩放的正确配置方法/
    - name: 6818开发板使用网络
      link: /[13]6818开发板使用网络/
 - name: 内功修炼
   subnav:
   - name: C语言基础复习
     link: /C语言基础复习/
   - name: C语言数组与函数递归复习
     link: /C语言数组与函数递归复习/
   - name: C语言指针复习
     link: /C语言指针复习/
  #  - name: 正则表达式与bash
  #    link:
  #  - name: make和cmake编写
  #    link:
  #  - name: 文件IO与系统IO
  #    link:
  #  - name: lvgl学习
  #    link:
  #  - name: 进程间通信
  #    link:
  #  - name: 并发
  #    link:
  #  - name: 网络编程
  #    link:
  #  - name: 数据库
  #    link:
  #  - name: 
  #    link:
 - name: 项目实践
   subnav:
   - name: 2048（c|ARM|Linux|底层开发）
     link: /privacy-zh/
   - name: 2048（c|ARM|Linux|LVGL）
     link: /privacy-zh/
 - name: 行动积炭
   subnav:
   - name: 本版块来源说明
     link: /[鸡汤]本版块来源说明/
   - name: 不行动等于慢性死亡
     link: /[鸡汤]不行动等于慢性死亡/
   - name: 把行动设置成你的默认模式
     link: /[鸡汤]把行动设置成你的默认模式/
   - name: 什么都不想做怎么办
     link: /[鸡汤]什么都不想做怎么办/
 - name: 其他内容
   subnav:
   - name: 隐私政策
     link: /privacy-zh/


encoding: UTF-8
filesystem_encoding: UTF-8